name: lookaround_iterator
version: 1.0.1+1
author: Philipp Schiffmann <philippschiffmann93@gmail.com>
description: Provides an iterator class with lookbehind and lookahead buffer.
homepage: https://github.com/pschiffmann/lookaround-iterator.dart
environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  test: ^1.0.0
