name: lookaround_iterator
version: 1.0.1
author: Philipp Schiffmann <philippschiffmann93@gmail.com>
description: Provides an iterator class with lookbehind and lookahead buffer.
homepage: https://github.com/pschiffmann/lookaround-iterator.dart
dev_dependencies:
  test: ^0.12.0
